apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appname }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appname }}
  labels:
    k8s-app: {{ .Values.appname }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  - "nodes/proxy"
  verbs:
  - "get"
  - "watch"
  - "list"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appname }}
  labels:
    k8s-app: {{ .Values.appname }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.appname }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appname }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.appname }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - name: fwd-input
          containerPort: {{ .Values.container.unsecureport }}
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
      volumes:
      - name: config-volume
        configMap:
          name: "{{ .Values.appname }}"
      serviceAccountName: {{ .Values.appname }}

