apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentdforwarder.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.fluentdforwarder.name }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.fluentdforwarder.name }}
  labels:
    k8s-app: {{ .Values.fluentdforwarder.name }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  - "nodes/proxy"
  verbs:
  - "get"
  - "watch"
  - "list"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.fluentdforwarder.name }}
  labels:
    k8s-app: {{ .Values.fluentdforwarder.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.fluentdforwarder.name }}
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.fluentdforwarder.name }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentdforwarder.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.fluentdforwarder.name }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.fluentdforwarder.name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.fluentdforwarder.name }}
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{ .Values.fluentdforwarder.name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Values.fluentdforwarder.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: {{ .Values.fluentdforwarder.name }}
      imagePullSecrets:
      - name: jlldataplatform 
