apiVersion: apps/v1
kind: Deployment
metadata:
  name: "example-prom-jmx-exp"
spec:
  labelSelector:
    app: demo-app
  config:
    configMapName: jmx-exporter-config
    configMapKey: config.yaml
  port: 9400