apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
      annotations:
        prometheus.io/slave: slaveA
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: helloweb
#   labels:
#     app: hello
# spec:
#   selector:
#     matchLabels:
#       app: hello
#       tier: web
#   template:
#     metadata:
#       # annotations:
#       #   prometheus.io/slave: slaveA
#       labels:
#         app: hello
#         tier: web
#     spec:
#       containers:
#       - name: hello-app
#         image: gcr.io/google-samples/hello-app:1.0
#         ports:
#         - containerPort: 8080

# # ---
# # apiVersion: apps/v1beta1
# # kind: Deployment
# # metadata:
# #   name: hello-deployment
# # spec:
# #   replicas: 1
# #   template:
# #     metadata:
# #       annotations:
# #         prometheus.io/slave: slaveA
# #       labels:
# #         run: hello-world
# #     spec:
# #       containers:
# #       - name: hello
# #         image: nginxdemos/hello:latest
# #         ports:
# #         - containerPort: 80
