apiVersion: v1
kind: Service
metadata:
  name: kafka-stream-service
  labels:
    app: kafka-streams
spec:
  type: ClusterIP
  ports:
    - port: 9042
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector:
    app: kafka-streams