kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
# kind: Service
# apiVersion: v1
# metadata:
#   name: elasticsearch
#   namespace: elk
# spec:
#   selector:
#     app: elasticsearch
#   ports:
#   - protocol: TCP
#     port: 9200
#     targetPort: db

