apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configFileName }}
  labels:
    name: {{ .Values.configFileName }}
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:

      - job_name: 'kubernetes-nodes'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
          
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          regex: '^.*bastion.*$'
          action: drop
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: '^.*9094.*$'
          action: drop
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: '^.*7071.*$'
          action: drop
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: kubernetes_node_name
          
      - job_name: 'kafka-{{ .Values.env }}'
        static_configs:
          - targets: 
            - kafka-0.kf-hs.default.svc.cluster.local:7071
            - kafka-1.kf-hs.default.svc.cluster.local:7071
            - kafka-2.kf-hs.default.svc.cluster.local:7071
        
      - job_name: 'kubernetes-cadvisor'

        # Default to scraping over https. If required, just disable this or change to
        # `http`.
        scheme: https

        # This TLS & bearer token file config is used to connect to the actual scrape
        # endpoints for cluster components. This is separate to discovery auth
        # configuration because discovery & scraping are two separate concerns in
        # Prometheus. The discovery auth config is automatic if Prometheus runs inside
        # the cluster. Otherwise, more config options have to be provided within the
        # <kubernetes_sd_config>.
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
          
      - job_name: 'Nifi-{{ .Values.env }}'
        static_configs:
        - targets:
          - {{ .Values.nodeIP.Nifi }}

      - job_name: 'Tableau-{{ .Values.env }}'
        static_configs:
        - targets:
          - {{ .Values.nodeIP.Tableau_1 }}
          - {{ .Values.nodeIP.Tableau_2 }}
          - {{ .Values.nodeIP.Tableau_3 }}
          
      - job_name: 'Tableau-perf'
        static_configs:
        - targets:
          - {{ .Values.envIP.perf1 }}
          - {{ .Values.envIP.perf2 }}
          - {{ .Values.envIP.perf3 }}

