# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-server-conf
#   # namespace: monitoring
#   labels:
#     name: prometheus-server-conf
# data:
#   prometheus.yml: |-
#     global:
#       scrape_interval: 5m
#       scrape_timeout : 5m
#       evaluation_interval: 5m
#     rule_files:
#       - /etc/prometheus/prometheus.rules

#     scrape_configs:
#       - job_name: 'federate'
#         scrape_interval: 5m

#         honor_labels: true
#         metrics_path: /federate

#         params:
#           'match[]':
#             # - '{job="prometheus"}'
#             # - '{__name__=~"job:.*"}'
#             # - '{job="kubernetes-nodes"}'
#             # - '{job="kubernetes-cadvisor"}'
#             # - '{job="node_exporter"}'
#             - '{job="kubernetes-pods"}'

#         static_configs:
#           - targets:
#             - 52.173.194.57:80
#             - 168.61.170.7:80
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-agent-config
  labels:
    name: prometheus-agent-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: kubernetes_node_name
      
      - job_name: 'Nifi-dev'
        static_configs:
        - targets: ['10.1.0.8:9100']
      
      - job_name: 'Tableau-dev'
        static_configs:
        - targets: ['52.167.161.193:9100']
        
      - job_name: 'kubernetes-cadvisor'

        # Default to scraping over https. If required, just disable this or change to
        # `http`.
        scheme: https

        # This TLS & bearer token file config is used to connect to the actual scrape
        # endpoints for cluster components. This is separate to discovery auth
        # configuration because discovery & scraping are two separate concerns in
        # Prometheus. The discovery auth config is automatic if Prometheus runs inside
        # the cluster. Otherwise, more config options have to be provided within the
        # <kubernetes_sd_config>.
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
          

      # - job_name: 'Nifi-Preprod'
      #   static_configs:
      #   - targets: ['10.42.121.7:9100']

      # - job_name: 'Tableau-Preprod'
      #   static_configs:
      #   - targets:
      #     - 10.42.121.10:9100
      #     - 10.42.121.12:9100
      #     - 10.42.121.13:9100
 