apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  # namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5m
      scrape_timeout : 5m
      evaluation_interval: 5m
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
      - job_name: 'federate'
        scrape_interval: 5m

        honor_labels: true
        metrics_path: /federate

        params:
          'match[]':
            # - '{job="prometheus"}'
            # - '{__name__=~"job:.*"}'
            - '{job="kubernetes-nodes"}'
            - '{job="kubernetes-cadvisor"}'
            - '{job="kubernetes-pods"}'
            - '{job="kube-state-metrics"}'
            - '{job="Nifi-dev"}'
            - '{job="Nifi-Preprod"}'
            - '{job="Tableau-dev"}'
            - '{job="Tableau-prod"}'
            - '{job="Nifi-prod"}'
            - '{job="Tableau-Preprod"}'
            - '{job="kafka-dev"}'
            - '{job="kafka-preprod"}'
            - '{job="kafka-prod"}'
        static_configs:
          - targets:
            - 52.252.105.247:80
            - 52.252.101.29:80
            - 104.209.173.104:80
            - 40.122.171.31:80
