---
- include_vars: env.yaml

- name: Creates directory
  file:
    path: /opt/tabsetup/
    state: directory
    owner: root
    group: root
    mode: 0775


- name: downloading tableu package  files
  get_url:
    url: https://downloads.tableau.com/esdalt/2019.2.0/tableau-server-2019-2-0.x86_64.rpm
    dest: "/opt/tabsetup/"
    owner: "root"
    group: "root"
    mode: 0755

- name: copying script files
  copy:
    src: "{{ item }}"
    dest: /opt/tabsetup/
    owner: root
    mode: 0755
  with_fileglob:
    - /root/dp-red2-devops-ansible/ansible/roles/tableauslave2/files/*

- name:  copying certs file  creation
  command: sh -x bootstrap.sh '{{ sa }}' '{{ key }}'
  args:
    chdir: "/opt/tabsetup/"

- name:  Installing tableau slave server
  command: ./tab-slave-rh2-server.sh '{{ password }}'
  args:
    chdir: "/opt/tabsetup/"

- name:  creating ssl directory
  command: "{{ item }}"
  args:
    chdir: "/var/opt/tableau/tableau_server/data/"
  with_items:
     - mkdir ssl
     - chown tableau:tableau ssl

- name:  copying certs file 
  command: sh -x cert.sh '{{ sa }}' '{{ key }}'
  args:
    chdir: "/opt/tabsetup/"
