apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configFileName }}
  labels:
    name: {{ .Values.configFileName }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5m
      scrape_timeout : 5m
      evaluation_interval: 5m
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
      - job_name: 'federate'
        scrape_interval: 5m

        honor_labels: true
        metrics_path: /federate

        params:
          'match[]':
            - '{job="kubernetes-nodes"}'
            - '{job="kubernetes-cadvisor"}'
            - '{job="kubernetes-pods"}'
            - '{job="kube-state-metrics"}'
            - '{job="Nifi-dev"}'
            - '{job="Nifi-Preprod"}'
            - '{job="Tableau-dev"}'
            - '{job="Tableau-prod"}'
            - '{job="Nifi-prod"}'
            - '{job="Tableau-Preprod"}'
            - '{job="kafka-dev"}'
            - '{job="kafka-preprod"}'
            - '{job="kafka-prod"}'
            - '{job="Nifi-sales"}'
            - '{job="Tableau-sales"}'
            - '{job="Tableau-perf"}'

        static_configs:
          - targets:
            - {{ .Values.envIP.sandbox}}:80
            - {{ .Values.envIP.dev}}:80
            - {{ .Values.envIP.preprod}}:80
            - {{ .Values.envIP.prod}}:80
            - {{ .Values.envIP.sales}}:80
          
