apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  # namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5m
      scrape_timeout : 5m
      evaluation_interval: 5m
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
      - job_name: 'federate'
        scrape_interval: 5m

        honor_labels: true
        metrics_path: /federate

        params:
          'match[]':
            # - '{job="prometheus"}'
            # - '{__name__=~"job:.*"}'
            - '{job="kubernetes-nodes"}'
            - '{job="kubernetes-cadvisor"}'
            - '{job="kubernetes-pods"}'
            - '{job="kube-state-metrics"}'
            - '{job="Nifi-dev"}'
            - '{job="Nifi-Preprod"}'
            - '{job="Tableau-dev"}'
            - '{job="Tableau-prod"}'
            - '{job="Nifi-prod"}'
            - '{job="Tableau-Preprod"}'
            - '{job="kafka-dev"}'
            - '{job="kafka-preprod"}'
            - '{job="kafka-prod"}'
        static_configs:
          - targets:
            - 20.69.212.58:80
            - 20.75.106.32:80
            - 20.85.56.49:80
            - 104.209.173.104:80
            - 23.99.255.76:80
      - job_name: 'Tableau-perf'
        static_configs:
        - targets:
          - 10.42.126.220:9100
          - 10.42.126.221:9100
          - 10.42.126.222:9100