# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: efk

spec:
  serviceName: elasticsearch-logging
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-logging
  template:
    metadata:
      labels:
        app: elasticsearch-logging
    spec:
    #   serviceAccountName: elasticsearch-logging
    #   # Elasticsearch requires vm.max_map_count to be at least 262144.
    #   # If your OS already sets up this number to a higher value, feel free
    #   # to remove this init container.
    #   initContainers:
    #   - image: alpine:3.6
    #     command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
    #     name: elasticsearch-logging-init
    #     securityContext:
    #       privileged: true
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        # imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_MASTER
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms8g -Xmx8g
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-logging
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 200Gi
