apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: default
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
        - name: kibana-logging
          image: mayadataio/kibana:f960e137
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          env:
            - name: SERVER_BASEPATH
              value: /kibana
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
      imagePullSecrets:
      - name: mayadatasecret
